export const data = [
{
    ID: 1,
    Type: "Pistol",
    Name: "Glock 19",
    BarrelSize: "4.01 inch",
    GunLength: "7.36 inch",
    Frame: "Polymer",
    UnloadedWeight: "20.99 ounces",
    MagazineSize: "15 bullets",
    Ammo: "9mm rounds",
    TriggerPull: "5.5 pounds",
    Img: ""
},
{
    ID: 2,
    Type: "Pistol",
    Name: "The CZ 75B",
    BarrelSize: "4.7 inch",
    GunLength: "8.12 inch",
    Frame: "Aluminum",
    UnloadedWeight: "32 ounces",
    MagazineSize: "9 bullets",
    Ammo: "19mm or 21mm rounds",
    TriggerPull: "4.5 pounds",
    Img: ""
},
{
    ID: 3,
    Type: "Pistol",
    Name: "The S & W Shield",
    BarrelSize: "5.25 inch",
    GunLength: " inch",
    Frame: "Polymer",
    UnloadedWeight: "20.8 ounces",
    MagazineSize: "8 bullets",
    Ammo: "19mm rounds",
    TriggerPull: "6.5 pounds",
    Img: ""
},
{
    ID: 4,
    Type: "Pistol",
    Name: "Springfield XD(M) Competition Series",
    BarrelSize: "3.1 inch",
    GunLength: "6.75 inch",
    Frame: "Polymer",
    UnloadedWeight: "31 ounces",
    MagazineSize: "19 bullets",
    Ammo: "9mm rounds, .40 S & W,.45 ACP, 10mm",
    TriggerPull: "5.25 pounds",
    Img: ""
},
{
    ID: 5,
    Type: "Pistol",
    Name: "Glock 19",
    BarrelSize: "4.01 inch",
    GunLength: "7.36 inch",
    Frame: "Polymer",
    UnloadedWeight: "20.99 ounces",
    MagazineSize: "15 bullets",
    Ammo: "9mm rounds",
    TriggerPull: "5.5 pounds",
    Img: ""
},
{       
    ID: 6,
    Type: "Pistol",
    Name: "The CZ 75B",
    BarrelSize: "4.7 inch",
    GunLength: "8.12 inch",
    Frame: "Aluminum",
    UnloadedWeight: "32 ounces",
    MagazineSize: "9 bullets",
    Ammo: "19mm or 21mm rounds",
    TriggerPull: "4.5 pounds",
    Img: ""
},
{
    ID: 7,
    Type: "Pistol",
    Name: "The S & W Shield",
    BarrelSize: "5.25 inch",
    GunLength: " inch",
    Frame: "Polymer",
    UnloadedWeight: "20.8 ounces",
    MagazineSize: "8 bullets",
    Ammo: "19mm rounds",
    TriggerPull: "6.5 pounds",
    Img: ""
},
{
    ID: 8,
    Type: "Pistol",
    Name: "Springfield XD(M) Competition Series",
    BarrelSize: "3.1 inch",
    GunLength: "6.75 inch",
    Frame: "Polymer",
    UnloadedWeight: "31 ounces",
    MagazineSize: "19 bullets",
    Ammo: "9mm rounds, .40 S & W,.45 ACP, 10mm",
    TriggerPull: "5.25 pounds",
    Img: ""
},
{

    ID: 9,
    Type: "Pistol",
    Name: "Glock 19",
    BarrelSize: "4.01 inch",
    GunLength: "7.36 inch",
    Frame: "Polymer",
    UnloadedWeight: "20.99 ounces",
    MagazineSize: "15 bullets",
    Ammo: "9mm rounds",
    TriggerPull: "5.5 pounds",
    Img: ""
},
{
    ID: 10,
    Type: "Pistol",
    Name: "The CZ 75B",
    BarrelSize: "4.7 inch",
    GunLength: "8.12 inch",
    Frame: "Aluminum",
    UnloadedWeight: "32 ounces",
    MagazineSize: "9 bullets",
    Ammo: "19mm or 21mm rounds",
    TriggerPull: "4.5 pounds",
    Img: ""
},
{
    ID: 11,
    Type: "Pistol",
    Name: "The S & W Shield",
    BarrelSize: "5.25 inch",
    GunLength: " inch",
    Frame: "Polymer",
    UnloadedWeight: "20.8 ounces",
    MagazineSize: "8 bullets",
    Ammo: "19mm rounds",
    TriggerPull: "6.5 pounds",
    Img: ""
},
{
    ID: 12,
    Type: "Pistol",
    Name: "Springfield XD(M) Competition Series",
    BarrelSize: "3.1 inch",
    GunLength: "6.75 inch",
    Frame: "Polymer",
    UnloadedWeight: "31 ounces",
    MagazineSize: "19 bullets",
    Ammo: "9mm rounds, .40 S & W,.45 ACP, 10mm",
    TriggerPull: "5.25 pounds",
    Img: ""
},
{
    ID: 14,
    Type: "Pistol",
    Name: "Glock 19",
    BarrelSize: "4.01 inch",
    GunLength: "7.36 inch",
    Frame: "Polymer",
    UnloadedWeight: "20.99 ounces",
    MagazineSize: "15 bullets",
    Ammo: "9mm rounds",
    TriggerPull: "5.5 pounds",
    Img: ""
},
{
    ID: 15,
    Type: "Pistol",
    Name: "The CZ 75B",
    BarrelSize: "4.7 inch",
    GunLength: "8.12 inch",
    Frame: "Aluminum",
    UnloadedWeight: "32 ounces",
    MagazineSize: "9 bullets",
    Ammo: "19mm or 21mm rounds",
    TriggerPull: "4.5 pounds",
    Img: ""
},
{
    ID: 16,
    Type: "Pistol",
    Name: "The S & W Shield",
    BarrelSize: "5.25 inch",
    GunLength: " inch",
    Frame: "Polymer",
    UnloadedWeight: "20.8 ounces",
    MagazineSize: "8 bullets",
    Ammo: "19mm rounds",
    TriggerPull: "6.5 pounds",
    Img: ""
},
{
    ID: 17,
    Type: "Pistol",
    Name: "Springfield XD(M) Competition Series",
    BarrelSize: "3.1 inch",
    GunLength: "6.75 inch",
    Frame: "Polymer",
    UnloadedWeight: "31 ounces",
    MagazineSize: "19 bullets",
    Ammo: "9mm rounds, .40 S & W,.45 ACP, 10mm",
    TriggerPull: "5.25 pounds",
    Img: ""
}
]